spring.application.name=todo-lists

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

supabase.jwt.secret=${JWT_SECRET}
supabase.url=${DB_URL}
supabase.service.key=${SUPABASE_SERVICE_KEY}
supabase.anon.key=${SUPABASE_ANON_KEY}